export interface BackendProjectPayload { projectId:string; projectName:string; state?:string; constituency?:string; mpName?:string; agency?:string; riskScore?:number; riskLevel?:string; factors?:unknown[]; recommendations?:string[]; financial?:Record<string,unknown>; progress?:Record<string,unknown>; raw?:Record<string,unknown>; }
export interface BackendAction { id:string; project_id:string; project_name?:string; risk_score:number; risk_level:string; recommended_action:string; authority:string; priority:string; deadline:string; status:string; created_at:string; notified_at?:string|null; notes?:string|null; local?:boolean; }
export interface BackendHealth { status:string; database:string; emailConfigured:boolean; aiProviderConfigured:boolean; }
export interface EmailTestResult { configured:boolean; sent:boolean; recipient?:string; error?:string; }

const ACTION_KEY='mplads-local-actions';
function readLocal():BackendAction[]{try{return JSON.parse(localStorage.getItem(ACTION_KEY)||'[]') as BackendAction[]}catch{return[]}}
function writeLocal(a:BackendAction[]){localStorage.setItem(ACTION_KEY,JSON.stringify(a.slice(0,500)))}
function localAction(project:BackendProjectPayload,deadlineDays=7):BackendAction{const score=Number(project.riskScore||0);const level=String(project.riskLevel||'medium');const id=`LOCAL-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;return {id,project_id:project.projectId,project_name:project.projectName,risk_score:score,risk_level:level,recommended_action:(project.recommendations?.[0] as string)||'Review project records and supporting evidence.',authority:level==='critical'||level==='high'?'District Authority':'Monitoring Authority',priority:score>=75?'URGENT':score>=50?'HIGH':score>=25?'MEDIUM':'LOW',deadline:new Date(Date.now()+Math.max(1,deadlineDays)*86400000).toISOString(),status:'DETECTED',created_at:new Date().toISOString(),notes:null,local:true}}

export function getApiBaseUrl(): string { try { const saved=JSON.parse(localStorage.getItem('mplads-app-settings')||'{}'); if(saved.apiBaseUrl)return String(saved.apiBaseUrl).replace(/\/$/,''); } catch {} return String(import.meta.env.VITE_API_BASE_URL||'http://localhost:8000').replace(/\/$/,''); }
async function request<T>(path:string,init?:RequestInit,baseOverride?:string):Promise<T>{const base=String(baseOverride||getApiBaseUrl()).replace(/\/$/,'');const res=await fetch(`${base}${path}`,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const text=await res.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{body={detail:text}}if(!res.ok)throw new Error(body?.detail||`Request failed (${res.status})`);return body as T}
export async function getBackendHealth(baseOverride?:string){return request<BackendHealth>('/api/health',undefined,baseOverride)}
export const backendHealth=getBackendHealth;
export async function createBackendAction(project:BackendProjectPayload,deadlineDays=7){try{return await request<any>('/api/actions',{method:'POST',body:JSON.stringify({project,deadlineDays})})}catch{const a=localAction(project,deadlineDays);const xs=readLocal();writeLocal([a,...xs]);return {actionId:a.id,...a,offline:true}}}
export async function getBackendActions(){try{const remote=await request<{actions:BackendAction[]}>('/api/actions');const local=readLocal();if(local.length){const remoteIds=new Set(remote.actions.map(a=>a.id));const merged=[...remote.actions,...local.filter(a=>!remoteIds.has(a.id))];return {actions:merged}}return remote}catch{return {actions:readLocal()}}}
export async function updateBackendAction(id:string,status:string,notes=''){try{return await request<any>(`/api/actions/${encodeURIComponent(id)}?status=${encodeURIComponent(status)}&notes=${encodeURIComponent(notes)}`,{method:'PATCH'})}catch{const xs=readLocal().map(a=>a.id===id?{...a,status,notes}:a);writeLocal(xs);return {actionId:id,status,local:true}}}
export async function notifyAuthority(actionId:string,recipients:string[],subject?:string,message?:string){return request<any>('/api/notifications/email',{method:'POST',body:JSON.stringify({actionId,recipients,subject,message})})}
export async function testAuthorityEmail(recipient:string){return request<EmailTestResult>('/api/notifications/test-email',{method:'POST',body:JSON.stringify({recipient})})}
export async function getBackendNotifications(){return request<{notifications:any[]}>('/api/notifications')}
export async function getBackendProjects(){return request<{projects:any[]}>('/api/projects')}
