import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, RefreshCw, ShieldAlert, Save, Mail, Search, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '@/components/common/PageHeader';
import { getBackendActions, updateBackendAction, notifyAuthority, type BackendAction } from '@/services/backendApi';

const statuses=['DETECTED','NOTIFIED','ASSIGNED','UNDER_INVESTIGATION','ACTION_TAKEN','VERIFIED','CLOSED','ESCALATED'];
export function ActionCenter(){
 const [actions,setActions]=useState<BackendAction[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(''); const [notes,setNotes]=useState<Record<string,string>>({}); const [email,setEmail]=useState<Record<string,string>>({}); const [message,setMessage]=useState(''); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('ALL');
 const load=async()=>{try{setError('');const d=await getBackendActions();setActions(d.actions??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load actions.')} }; useEffect(()=>{void load();const t=setInterval(()=>void load(),30000);return()=>clearInterval(t)},[]);
 const filtered=useMemo(()=>actions.filter(a=>(filter==='ALL'||a.status===filter)&&`${a.project_id} ${a.project_name??''} ${a.authority} ${a.priority} ${a.status}`.toLowerCase().includes(query.toLowerCase())),[actions,filter,query]);
 const update=async(a:BackendAction)=>{setBusy(a.id);try{await updateBackendAction(a.id,a.status,notes[a.id]??a.notes??'');await load();setMessage('Action updated successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Update failed.')}finally{setBusy('')}};
 const notify=async(a:BackendAction)=>{const to=(email[a.id]||'').split(',').map(x=>x.trim()).filter(Boolean);if(!to.length){setMessage('Enter at least one authority email.');return}setBusy(a.id);try{const r=await notifyAuthority(a.id,to);setMessage(r.results?.some((x:any)=>x.status==='SENT')?'Notification sent successfully.':'Notification failed; verify SMTP configuration.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Notification failed. Start FastAPI and check SMTP.')}finally{setBusy('')}};
 const openCount=actions.filter(a=>!['CLOSED','VERIFIED'].includes(a.status)).length;
 return <div className="page-shell space-y-5"><PageHeader title="Action Center" description="Persistent review actions, assignment, status tracking and authority notifications." action={<button onClick={()=>void load()} className="action-secondary"><RefreshCw size={14}/>Refresh</button>}/>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Kpi label="Open actions" value={openCount}/><Kpi label="Total actions" value={actions.length}/><Kpi label="Escalated" value={actions.filter(a=>a.status==='ESCALATED').length}/><Kpi label="Closed" value={actions.filter(a=>a.status==='CLOSED').length}/></div>
  {message&&<div className="notice-success"><CheckCircle2 size={15}/>{message}</div>}{error&&<div className="notice-warning">Backend unavailable; Action Center is using local browser actions where possible. {error}</div>}
  <div className="panel p-4"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="control w-full pl-9" placeholder="Search project, authority, priority..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="control md:w-56"><option value="ALL">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div>
  <div className="space-y-3">{filtered.length===0?<div className="panel p-10 text-center"><ShieldAlert className="mx-auto text-slate-400" size={30}/><p className="mt-3 text-sm font-semibold text-slate-800 dark:text-slate-100">No matching actions</p><p className="mt-1 text-xs text-slate-500">Create a review action from Alerts, Duplicate Detection, Reports or Project Investigation.</p></div>:filtered.map(a=><div key={a.id} className="panel p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">{a.priority}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-medium text-slate-700 dark:bg-slate-800 dark:text-slate-200">{a.status}</span>{a.local&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-700 dark:bg-amber-950/40 dark:text-amber-300">LOCAL</span>}</div><h3 className="mt-2 break-words text-sm font-semibold text-slate-900 dark:text-slate-100">{a.recommended_action}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Project: {a.project_id} · Authority: {a.authority}</p></div><div className="shrink-0 text-right"><p className="text-2xl font-bold text-slate-900 dark:text-slate-100">{Number(a.risk_score||0).toFixed(0)}</p><p className="text-[10px] uppercase tracking-wide text-slate-400">Risk</p></div></div><div className="mt-3 grid grid-cols-1 gap-3 border-t border-slate-100 pt-3 dark:border-slate-800 md:grid-cols-3"><Info icon={ShieldAlert} label="Risk level" value={a.risk_level}/><Info icon={Clock3} label="Deadline" value={a.deadline?new Date(a.deadline).toLocaleDateString('en-IN'):'—'}/><Info icon={CheckCircle2} label="Created" value={a.created_at?new Date(a.created_at).toLocaleString('en-IN'):'—'}/></div><div className="mt-4 grid grid-cols-1 gap-2 lg:grid-cols-[1fr_260px_auto]"><select value={a.status} onChange={e=>setActions(xs=>xs.map(x=>x.id===a.id?{...x,status:e.target.value}:x))} className="control">{statuses.map(s=><option key={s}>{s}</option>)}</select><input value={notes[a.id]??a.notes??''} onChange={e=>setNotes(x=>({...x,[a.id]:e.target.value}))} placeholder="Review note / investigation outcome" className="control"/><button disabled={busy===a.id} onClick={()=>void update(a)} className="action-primary"><Save size={13}/>Save</button></div><div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={email[a.id]??''} onChange={e=>setEmail(x=>({...x,[a.id]:e.target.value}))} placeholder="authority@example.gov.in (comma separated)" className="control"/><button disabled={busy===a.id} onClick={()=>void notify(a)} className="action-secondary"><Mail size={13}/>Notify</button><Link to={`/projects/${encodeURIComponent(a.project_id)}`} className="action-secondary"><ExternalLink size={13}/>Investigate</Link></div></div>)}</div>
 </div>;
}
function Kpi({label,value}:{label:string;value:number}){return <div className="kpi-card"><span className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</span><strong className="mt-2 block text-2xl text-slate-900 dark:text-white">{value.toLocaleString('en-IN')}</strong></div>}
function Info({icon:Icon,label,value}:{icon:typeof ShieldAlert;label:string;value:string}){return <div className="flex items-start gap-2"><Icon size={14} className="mt-0.5 text-slate-400"/><div><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-0.5 text-xs font-medium text-slate-700 dark:text-slate-300">{value}</p></div></div>}
