import { useMemo, useState } from 'react';
import { useTheme } from '@/hooks/useTheme';
import { AlertTriangle, Building2, CheckCircle2, IndianRupee, Search, TrendingUp } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { useCurrentDataset } from '@/services/datasetStore';
import { analyzeAgencyPerformance } from '@/services/agencyPerformanceEngine';
import { formatCrore } from '@/utils/formatters';
const badge=(s:number)=>s>=85?'bg-emerald-50 text-emerald-700':s>=70?'bg-blue-50 text-blue-700':s>=50?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700';
export function AgencyPerformance(){
 const {theme}=useTheme(); const dataset=useCurrentDataset(); const [q,setQ]=useState(''); const [level,setLevel]=useState('All');
 const agencies=useMemo(()=>dataset?analyzeAgencyPerformance(dataset.rows):[],[dataset]);
 const filtered=useMemo(()=>agencies.filter(a=>(!q||a.agency.toLowerCase().includes(q.toLowerCase()))&&(level==='All'||a.performanceLevel===level)),[agencies,q,level]);
 const stats=useMemo(()=>({count:agencies.length,projects:agencies.reduce((s,a)=>s+a.projectCount,0),s:agencies.reduce((s,a)=>s+a.sanctionedAmount,0),e:agencies.reduce((s,a)=>s+a.expenditure,0),attention:agencies.filter(a=>a.performanceLevel==='Needs Attention').length}),[agencies]);
 const kpis=[{Icon:Building2,label:'Agencies',value:stats.count.toLocaleString('en-IN')},{Icon:CheckCircle2,label:'Projects',value:stats.projects.toLocaleString('en-IN')},{Icon:IndianRupee,label:'Sanctioned',value:formatCrore(stats.s)},{Icon:TrendingUp,label:'Expenditure',value:formatCrore(stats.e)},{Icon:AlertTriangle,label:'Needs Attention',value:stats.attention.toLocaleString('en-IN')}];
 if(!dataset)return <div className="page-shell"><PageHeader title="Agency Performance" description="Comparative performance metrics for implementing agencies."/><div className="panel"><EmptyState icon={Building2} title="No agency data available" description="Upload and process an MPLADS dataset first."/></div></div>;
 const chart=agencies.slice().sort((a,b)=>b.performanceScore-a.performanceScore).slice(0,10).map(a=>({name:a.agency.length>18?a.agency.slice(0,18)+'…':a.agency,score:a.performanceScore}));
 return <div className="page-shell space-y-5">
  <PageHeader title="Agency Performance" description="Compare implementation performance, fund utilization, progress and delay indicators."/>
  <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-4">
   {kpis.map(({Icon,label,value})=><div className="kpi-card" key={label}><div className="flex items-center justify-between text-slate-500"><span className="text-xs font-medium uppercase tracking-wide">{label}</span><Icon size={18}/></div><div className="mt-3 text-xl sm:text-2xl font-bold text-slate-900 break-words">{value}</div></div>)}
  </div>
  <div className="panel"><div className="mb-4"><h2 className="section-title">Agency Performance Score</h2><p className="section-subtitle">Top agencies by explainable analytical score.</p></div><div className="h-[260px] sm:h-[320px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:5,right:10,left:-15,bottom:45}}><CartesianGrid strokeDasharray="3 3" stroke="var(--chart-grid)"/><XAxis dataKey="name" angle={-30} textAnchor="end" interval={0} tick={{fontSize:10,fill:"var(--chart-text)"}}/><YAxis domain={[0,100]} tick={{fill:"var(--chart-text)"}}/><Tooltip contentStyle={{backgroundColor:"var(--chart-tooltip-bg)",border:"1px solid var(--surface-border)",borderRadius:8}} labelStyle={{color:"var(--chart-tooltip-text)"}} itemStyle={{color:theme==='dark'?'#a5b4fc':'#4338ca'}}/><Bar dataKey="score" name="Performance Score" fill="#6366f1" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div>
  <div className="panel p-3 sm:p-4"><div className="flex flex-col sm:flex-row gap-3"><div className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search agency..." className="control w-full pl-9"/></div><select value={level} onChange={e=>setLevel(e.target.value)} className="control w-full sm:w-56"><option>All</option><option>Excellent</option><option>Good</option><option>Moderate</option><option>Needs Attention</option></select></div></div>
  <div className="panel overflow-hidden"><div className="table-scroll"><table className="data-table min-w-[1050px]"><thead><tr><th>Agency</th><th>Projects</th><th>Utilization</th><th>Progress</th><th>Delayed</th><th>Cost Overrun</th><th>Score</th><th>Status</th></tr></thead><tbody>{filtered.map(a=><tr key={a.agency}><td className="max-w-[280px]"><div className="font-medium truncate">{a.agency}</div><div className="text-[11px] text-slate-500 truncate">{a.reasons[0]}</div></td><td>{a.projectCount}</td><td>{a.utilization.toFixed(1)}%</td><td>{a.averagePhysicalProgress.toFixed(1)}%</td><td>{a.delayedProjects}</td><td>{a.costOverrunProjects}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge(a.performanceScore)}`}>{a.performanceScore}</span></td><td><span className={`rounded-full px-2 py-1 text-xs font-medium ${badge(a.performanceScore)}`}>{a.performanceLevel}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No agencies match your filters.</td></tr>}</tbody></table></div></div>
  <div className="panel"><h2 className="section-title">Scoring methodology</h2><p className="section-subtitle mt-1">Analytical prioritization only; a score is not proof of fraud or misconduct.</p><div className="mt-4 grid grid-cols-2 sm:grid-cols-5 gap-3 text-center">{[['30%','Completion'],['25%','Utilization'],['20%','Progress'],['15%','Delay control'],['10%','Cost control']].map(([v,l])=><div className="rounded-lg bg-slate-50 p-3" key={l}><b className="text-lg">{v}</b><div className="text-[11px] text-slate-500">{l}</div></div>)}</div></div>
 </div>;
}
