import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Copy, Search, ShieldAlert, GitCompareArrows, Plus, Loader2 } from 'lucide-react';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { RiskBadge } from '@/components/common/RiskBadge';
import { useCurrentDataset } from '@/services/datasetStore';
import { detectDuplicates } from '@/services/duplicateDetector';
import { createBackendAction } from '@/services/backendApi';
import { useSettings } from '@/hooks/useSettings';
import type { RawRow } from '@/types/dataset';

const s=(v:unknown)=>String(v??'').trim();
const money=(v:unknown)=>{const n=Number(String(v??'').replace(/[₹$€£,\s]/g,''));return Number.isFinite(n)?n:null;};
const norm=(v:unknown)=>s(v).toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const fmt=(v:unknown)=>{const n=money(v);return n===null?'—':`₹${n.toLocaleString('en-IN',{maximumFractionDigits:0})}`};

export function DuplicateDetection(){
 const dataset=useCurrentDataset(); const {settings}=useSettings(); const [query,setQuery]=useState(''); const [kind,setKind]=useState<'all'|'exact'|'strong'|'potential'>('all'); const [selected,setSelected]=useState<{a:number;b:number}|null>(null); const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState('');
 const result=useMemo(()=>dataset?detectDuplicates(dataset.rows as RawRow[],{strongThreshold:settings.duplicateStrongThreshold,potentialThreshold:settings.duplicatePotentialThreshold,amountTolerancePercent:settings.duplicateAmountTolerance}):null,[dataset,settings.duplicateStrongThreshold,settings.duplicatePotentialThreshold,settings.duplicateAmountTolerance]);
 const filtered=useMemo(()=>result&&dataset?result.pairs.filter(p=>kind==='all'||p.kind===kind).filter(p=>{if(!query)return true;const a=dataset.rows[p.a],b=dataset.rows[p.b],q=norm(query);return [a.project_name,a.work_description,a.state,a.constituency,a.mp_name,b.project_name,b.work_description,b.state,b.constituency,b.mp_name].some(v=>norm(v).includes(q));}).slice(0,settings.maxRowsPerTable):[],[result,dataset,kind,query,settings.maxRowsPerTable]);
 if(!dataset||!result)return <div className="max-w-screen-2xl mx-auto"><PageHeader title="Duplicate Detection" description="Evidence-based similarity screening for potentially duplicate or overlapping MPLADS works."/><div className="panel"><EmptyState icon={Copy} title="No processed dataset" description="Upload and process an MPLADS dataset in Data Management first."/></div></div>;
 const createAction=async(a:RawRow,b:RawRow,key:string)=>{setBusy(key);setMessage('');try{const r=await createBackendAction({projectId:`duplicate-${a.source_row_number??''}-${b.source_row_number??''}`,projectName:`Duplicate review: ${s(a.project_name)||'Project A'} / ${s(b.project_name)||'Project B'}`,state:s(a.state),constituency:s(a.constituency),mpName:s(a.mp_name),riskScore:Math.max(50,result.pairs.find(p=>`${p.a}-${p.b}`===key)?.score??50),riskLevel:'high',factors:[{id:'duplicate',label:'Duplicate',score:20,max:20,reason:'Potentially overlapping project records require human verification.'}],recommendations:['Compare sanctions, work-site evidence, bills and completion records before any enforcement decision.']},7);setMessage(`Action ${r.actionId?.slice(0,8)||''} created for review.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not create backend action. Start FastAPI on port 8000.')}finally{setBusy(null)}};
 return <div className="max-w-screen-2xl mx-auto space-y-5">
  <PageHeader title="Duplicate Detection" description="Multi-signal duplicate screening with explainable confidence and human-review workflow."/>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat icon={Copy} label="Flagged rows" value={result.totalDuplicateRows}/><Stat icon={ShieldAlert} label="Exact groups" value={result.exactDuplicateGroups.length}/><Stat icon={AlertTriangle} label="Strong groups" value={result.strongDuplicateGroups.length}/><Stat icon={CheckCircle2} label="Potential groups" value={result.potentialDuplicateGroups.length}/></div>
  <div className="panel p-4 space-y-4">
   <div className="flex flex-col lg:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, constituency, MP..." className="control w-full pl-9"/></div><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} className="control"><option value="all">All match types</option><option value="exact">Exact</option><option value="strong">Strong</option><option value="potential">Potential</option></select></div>
   <div className="flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded-full bg-slate-100 px-2.5 py-1">Strong ≥ {settings.duplicateStrongThreshold}%</span><span className="rounded-full bg-slate-100 px-2.5 py-1">Potential ≥ {settings.duplicatePotentialThreshold}%</span><span className="rounded-full bg-slate-100 px-2.5 py-1">Amount tolerance {settings.duplicateAmountTolerance}%</span><span className="rounded-full bg-slate-100 px-2.5 py-1">Showing {filtered.length} pairs</span></div>
   <p className="text-xs text-slate-500">Similarity combines description/name overlap, location, MP/agency consistency and financial proximity. A flag is a review signal, not proof of fraud.</p>
   {message&&<div className="rounded-md bg-primary-50 px-3 py-2 text-xs font-medium text-primary-700">{message}</div>}
   <div className="table-scroll"><table className="data-table"><thead><tr><th>Similarity</th><th>Project A</th><th>Project B</th><th>Evidence</th><th>Action</th></tr></thead><tbody>
    {filtered.map((p,i)=>{const a=dataset.rows[p.a] as RawRow,b=dataset.rows[p.b] as RawRow;const key=`${p.a}-${p.b}`;return <tr key={key}><td><span className="text-base font-bold">{p.score}%</span><div className="mt-1"><RiskBadge level={p.kind==='exact'?'critical':p.kind==='strong'?'high':'medium'}/></div></td><td className="min-w-[260px]"><div className="font-semibold text-slate-800 dark:text-slate-100">{s(a.project_name)||'Unnamed project'}</div><div className="mt-1 text-xs text-slate-500 line-clamp-3">{s(a.work_description)||'No description'}</div><div className="mt-2 text-[10px] text-slate-400">{s(a.state)} · {s(a.constituency)} · {fmt(a.amount_disbursed)}</div></td><td className="min-w-[260px]"><div className="font-semibold text-slate-800 dark:text-slate-100">{s(b.project_name)||'Unnamed project'}</div><div className="mt-1 text-xs text-slate-500 line-clamp-3">{s(b.work_description)||'No description'}</div><div className="mt-2 text-[10px] text-slate-400">{s(b.state)} · {s(b.constituency)} · {fmt(b.amount_disbursed)}</div></td><td className="min-w-[220px]"><ul className="space-y-1 text-xs text-slate-600 dark:text-slate-300">{p.reasons.slice(0,4).map((r,j)=><li key={j}>• {r}</li>)}</ul></td><td><div className="flex flex-wrap gap-2"><button onClick={()=>setSelected({a:p.a,b:p.b})} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-100"><GitCompareArrows size={14}/>Compare</button><button disabled={busy===key} onClick={()=>createAction(a,b,key)} className="inline-flex items-center gap-1 rounded-md bg-primary-600 px-2.5 py-1.5 text-xs font-medium text-white hover:bg-primary-700 disabled:opacity-60">{busy===key?<Loader2 size={14} className="animate-spin"/>:<Plus size={14}/>}Action</button></div></td></tr>})}
    {!filtered.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">No duplicate candidates match the current filters.</td></tr>}
   </tbody></table></div>
  </div>
  {selected&&<CompareModal a={dataset.rows[selected.a] as RawRow} b={dataset.rows[selected.b] as RawRow} score={result.pairs.find(p=>p.a===selected.a&&p.b===selected.b)?.score??0} onClose={()=>setSelected(null)}/>} 
 </div>;
}
function CompareModal({a,b,score,onClose}:{a:RawRow;b:RawRow;score:number;onClose:()=>void}){const fields=[['Project',a.project_name,b.project_name],['Description',a.work_description,b.work_description],['State',a.state,b.state],['Constituency',a.constituency,b.constituency],['MP',a.mp_name,b.mp_name],['Amount',a.amount_disbursed,b.amount_disbursed],['Completion date',a.actual_completion_date,b.actual_completion_date],['Image / evidence',a.image,b.image]];return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onClick={onClose}><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-xl bg-white p-5 shadow-2xl dark:bg-slate-900" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-900 dark:text-white">Project comparison</h2><p className="text-xs text-slate-500">Similarity score: <strong>{score}%</strong></p></div><button onClick={onClose} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs text-slate-600 dark:border-slate-700 dark:text-slate-200">Close</button></div><div className="mt-4 grid grid-cols-[130px_1fr_1fr] border border-slate-200 text-xs dark:border-slate-700">{fields.map(([label,x,y])=><div key={label} className="contents"><div className="border-b border-slate-200 bg-slate-50 p-3 font-semibold text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300">{label}</div><div className="border-b border-slate-200 p-3 text-slate-800 dark:border-slate-700 dark:text-slate-100">{s(x)||'—'}</div><div className="border-b border-slate-200 p-3 text-slate-800 dark:border-slate-700 dark:text-slate-100">{s(y)||'—'}</div></div>)}</div></div></div>}
function Stat({icon:Icon,label,value}:{icon:typeof Copy;label:string;value:number}){return <div className="kpi-card"><Icon className="h-5 w-5 text-slate-500"/><div className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{value.toLocaleString('en-IN')}</div><div className="text-xs text-slate-500">{label}</div></div>}
