import { useMemo, useState } from 'react';
import { BrainCircuit, Clock3, IndianRupee, ShieldAlert, Target, Search, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { KPICard } from '@/components/common/KPICard';
import { ChartCard } from '@/components/charts/ChartCard';
import { RiskBadge } from '@/components/common/RiskBadge';
import { useCurrentDataset } from '@/services/datasetStore';
import { predictDataset, type ProjectPrediction } from '@/services/predictiveEngine';

const pct=(v:number)=>`${v}%`;
export function ProgressAnalytics(){
 const dataset=useCurrentDataset(); const analysis=useMemo(()=>dataset?predictDataset(dataset):null,[dataset]); const [query,setQuery]=useState('');
 const projects=useMemo(()=>{if(!analysis)return[];const q=query.toLowerCase();return analysis.topProjects.filter(p=>!q||`${p.projectId} ${p.projectName} ${p.state} ${p.constituency}`.toLowerCase().includes(q));},[analysis,query]);
 return <div className="max-w-screen-2xl mx-auto"><PageHeader title="Predictive Analytics & Early Warning" description="Explainable forecasts for delay, cost-overrun and completion risk using available project signals."/>
 {!dataset||!analysis?<div className="rounded-lg border border-slate-200 bg-white shadow-[var(--shadow-card)]"><EmptyState icon={BrainCircuit} title="No prediction data available" description="Upload and process an MPLADS dataset to generate early-warning predictions."/></div>:<>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-5"><KPICard title="Projects Scored" value={analysis.projects.toLocaleString('en-IN')} subtitle="Prediction coverage" icon={Target} iconClassName="bg-blue-50 text-blue-600"/><KPICard title="High Delay Risk" value={analysis.delayHigh.toLocaleString('en-IN')} subtitle="Probability ≥ 60%" icon={Clock3} iconClassName="bg-orange-50 text-orange-600"/><KPICard title="High Cost Risk" value={analysis.costHigh.toLocaleString('en-IN')} subtitle="Probability ≥ 60%" icon={IndianRupee} iconClassName="bg-red-50 text-red-600"/><KPICard title="Completion Risk" value={analysis.completionHigh.toLocaleString('en-IN')} subtitle="Risk ≥ 60%" icon={ShieldAlert} iconClassName="bg-purple-50 text-purple-600"/><KPICard title="Data Coverage" value={pct(analysis.coverage)} subtitle="Signals available" icon={BrainCircuit} iconClassName="bg-green-50 text-green-600"/></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-5"><ChartCard title="Average predicted risk" subtitle="Across processed projects"><div className="space-y-4 pt-2">{[['Delay probability',analysis.averageDelayProbability,'bg-orange-500'],['Cost-overrun probability',analysis.averageCostProbability,'bg-red-500'],['Completion risk',analysis.averageCompletionRisk,'bg-purple-500']].map(([label,v,c])=><div key={String(label)}><div className="flex justify-between text-xs mb-1"><span className="text-slate-600">{label}</span><b>{v}%</b></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className={`h-full ${c}`} style={{width:`${v}%`}}/></div></div>)}</div></ChartCard><div className="lg:col-span-2 rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><div className="flex items-center gap-2"><BrainCircuit size={16} className="text-primary-600"/><h3 className="text-sm font-semibold text-slate-800">How the prediction works</h3></div><p className="text-xs text-slate-500 mt-2">The early-warning score combines observable timeline, physical-progress, financial-progress and cost signals. It is an explainable screening model, not proof of future failure.</p><div className="grid sm:grid-cols-3 gap-3 mt-4">{[['Delay','Timeline + progress','Identifies projects likely to miss milestones.'],['Cost','Estimate + sanction + expenditure','Identifies projects approaching or exceeding financial limits.'],['Completion','Combined trajectory','Prioritizes projects needing intervention.']].map(x=><div className="rounded-lg bg-slate-50 p-3" key={x[0]}><p className="text-xs font-semibold text-slate-700">{x[0]}</p><p className="text-[11px] font-medium text-slate-600 mt-1">{x[1]}</p><p className="text-[10px] text-slate-400 mt-1">{x[2]}</p></div>)}</div></div></div>
 <section className="rounded-lg border border-slate-200 bg-white shadow-[var(--shadow-card)] overflow-hidden"><div className="p-4 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-slate-800">Priority early-warning queue</h3><p className="text-xs text-slate-500 mt-0.5">Projects with the strongest predicted intervention need.</p></div><div className="relative w-full sm:w-72"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, state, constituency..." className="h-9 w-full rounded-md border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-primary-400"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="text-left px-4 py-3">Project</th><th className="text-left">Location</th><th>Delay</th><th>Cost</th><th>Completion</th><th>Confidence</th><th>Risk</th><th>Recommended action</th><th></th></tr></thead><tbody>{projects.map((p:ProjectPrediction)=><tr key={`${p.rowIndex}-${p.projectId}`} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><p className="font-medium text-slate-800 max-w-[270px] truncate">{p.projectName}</p><p className="text-[10px] text-slate-400">{p.projectId}</p></td><td>{p.constituency||p.state||'—'}</td><td className="font-semibold">{p.delayProbability}%</td><td className="font-semibold">{p.costOverrunProbability}%</td><td className="font-semibold">{p.completionRisk}%</td><td>{p.confidence}%</td><td><RiskBadge level={p.riskLevel}/></td><td className="max-w-[280px] text-slate-500">{p.recommendedAction}</td><td className="pr-4"><Link to={`/projects/${encodeURIComponent(p.projectId)}`} state={{rowIndex:p.rowIndex}} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1.5 font-medium hover:border-primary-300"><ArrowUpRight size={12}/>View</Link></td></tr>)}</tbody></table></div>{!projects.length&&<EmptyState compact title="No matching predictions" description="Try a different search term."/>}</section></>}
 </div>;
}
