import { useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, CalendarClock, CheckCircle2, Copy, FileText, IndianRupee, MapPin, ShieldCheck, TrendingUp } from 'lucide-react';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { RiskBadge } from '@/components/common/RiskBadge';
import { StatusBadge } from '@/components/common/StatusBadge';
import { useCurrentDataset } from '@/services/datasetStore';
import { analyzeDataset, type ProjectRisk } from '@/services/riskEngine';

import { formatCrore } from '@/utils/formatters';
import { createBackendAction } from '@/services/backendApi';
const money = (v: number | null) => v == null ? '—' : formatCrore(v);
const text = (v: unknown) => String(v ?? '').trim() || '—';
const fmtDate = (v: unknown) => { const s = text(v); if (s === '—') return s; const d = new Date(s); return Number.isNaN(d.getTime()) ? s : d.toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }); };

export function ProjectInvestigation() {
  const { projectId } = useParams();
  const location = useLocation();
  const dataset = useCurrentDataset();
  const analysis = useMemo(() => dataset ? analyzeDataset(dataset) : null, [dataset]);
  const project = useMemo<ProjectRisk | null>(() => {
    if (!analysis) return null;
    const rowIndex = (location.state as { rowIndex?: number } | null)?.rowIndex;
    if (typeof rowIndex === 'number') {
      const byRow = analysis.projectRisks.find(p => p.rowIndex === rowIndex);
      if (byRow) return byRow;
    }
    return analysis.projectRisks.find(p => p.projectId === decodeURIComponent(projectId ?? '')) ?? null;
  }, [analysis, location.state, projectId]);
  const raw = project && dataset ? dataset.rows[project.rowIndex] : null;
  const storageKey = project ? `mplads-image-${project.projectId}` : '';
  const [customImage, setCustomImage] = useState<string | null>(() => storageKey ? localStorage.getItem(storageKey) : null);
  const sourceImage = customImage || (raw && text(raw.image) !== '—' ? text(raw.image) : `https://picsum.photos/seed/mplads-${encodeURIComponent(project?.projectId || 'project')}/900/560`);
  const uploadImage = (e: React.ChangeEvent<HTMLInputElement>) => { const file=e.target.files?.[0]; if(!file||!storageKey)return; const reader=new FileReader(); reader.onload=()=>{const v=String(reader.result); localStorage.setItem(storageKey,v);setCustomImage(v)}; reader.readAsDataURL(file); };
  const [actionBusy,setActionBusy] = useState(false);
  const [actionMessage,setActionMessage] = useState('');
  const createAction = async () => { setActionBusy(true); setActionMessage(''); try { const r=await createBackendAction({projectId:project.projectId,projectName:project.projectName,state:project.state,constituency:project.constituency,mpName:project.mpName,agency:project.agency,riskScore:project.riskScore,riskLevel:project.riskLevel,factors:project.factors,recommendations:project.recommendations,raw:raw as Record<string,unknown>},7); setActionMessage(`Action ${r.actionId?.slice(0,8)||''} created in Action Center.`); } catch(e){ setActionMessage(e instanceof Error?e.message:'Could not create action. Start the backend service.'); } finally { setActionBusy(false); } };
  const randomImage = () => { const v=`https://picsum.photos/seed/mplads-${project?.rowIndex}-${Date.now()}/900/560`; setCustomImage(v); if(storageKey)localStorage.setItem(storageKey,v); }; 

  if (!dataset || !analysis) return <div className="max-w-screen-2xl mx-auto"><PageHeader title="Project Investigation" /><div className="rounded-lg border border-slate-200 bg-white"><EmptyState icon={FileText} title="No processed dataset available" description="Upload and process an MPLADS dataset before investigating a project." action={<Link to="/data-management" className="rounded-md bg-primary-600 px-4 py-2 text-xs font-medium text-white">Go to Data Management</Link>} /></div></div>;
  if (!project || !raw) return <div className="max-w-screen-2xl mx-auto"><PageHeader title="Project Investigation" /><div className="rounded-lg border border-slate-200 bg-white"><EmptyState icon={AlertTriangle} title="Project not found" description="The selected project could not be found in the active dataset." action={<Link to="/projects" className="rounded-md border border-slate-200 px-4 py-2 text-xs font-medium text-slate-700">Back to Projects</Link>} /></div></div>;

  const factorTone = (score: number, max: number) => score / max >= .7 ? 'border-red-200 bg-red-50' : score > 0 ? 'border-amber-200 bg-amber-50' : 'border-slate-200 bg-slate-50';
  return <div className="max-w-screen-2xl mx-auto">
    <PageHeader title="Project Investigation" description="Evidence-oriented drill-down for a single MPLADS work." action={<Link to="/projects" className="inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50"><ArrowLeft size={14}/> Back to Projects</Link>} />
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[1fr_320px]">
      <main className="space-y-5">
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-[10px] uppercase tracking-wider text-slate-400">{project.projectId}</p><h1 className="mt-1 text-xl font-semibold text-slate-900">{project.projectName}</h1><div className="mt-2 flex flex-wrap gap-2"><RiskBadge level={project.riskLevel}/><StatusBadge status={project.status}/></div></div><div className="text-left md:text-right"><p className="text-4xl font-bold text-slate-900">{project.riskScore}</p><p className="text-[10px] uppercase tracking-wider text-slate-400">Overall risk score / 100</p></div></div><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="State" value={project.state}/><Info label="District" value={project.district}/><Info label="Constituency" value={project.constituency}/><Info label="MP" value={project.mpName}/><Info label="Implementing Agency" value={project.agency}/><Info label="Work Category" value={raw.work_category}/><Info label="House" value={raw.house}/><Info label="Source row" value={String(project.rowIndex + 1)}/></div></section>
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={IndianRupee} title="Financial investigation"/><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Estimated cost" value={money(num(raw.estimated_cost))}/><Metric label="Sanctioned cost" value={money(project.sanctionedAmount)}/><Metric label="Released / disbursed" value={money(num(raw.amount_released ?? raw.amount_disbursed))}/><Metric label="Expenditure" value={money(project.expenditure)}/><Metric label="Final cost" value={money(num(raw.final_cost))}/><Metric label="Utilization" value={project.sanctionedAmount && project.expenditure != null ? `${((project.expenditure/project.sanctionedAmount)*100).toFixed(1)}%` : '—'}/></div></section>
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={CalendarClock} title="Timeline & progress"/><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Recommendation" value={fmtDate(raw.recommendation_date)}/><Info label="Sanction" value={fmtDate(raw.sanction_date)}/><Info label="Start" value={fmtDate(raw.start_date)}/><Info label="Expected completion" value={fmtDate(raw.expected_completion_date ?? raw.expected_completion)}/><Info label="Actual completion" value={fmtDate(raw.actual_completion_date ?? raw.actual_completion)}/><Metric label="Physical progress" value={num(raw.physical_progress) == null ? '—' : `${num(raw.physical_progress)!.toFixed(1)}%`}/><Metric label="Financial progress" value={num(raw.financial_progress) == null ? '—' : `${num(raw.financial_progress)!.toFixed(1)}%`}/></div></section>
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={ShieldCheck} title="Why the AI flagged this project"/><div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">{project.factors.map(f=><div key={f.id} className={`rounded-lg border p-4 ${factorTone(f.score,f.max)}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-slate-800">{f.label}</p><p className="text-[10px] text-slate-400">{f.score} / {f.max} points</p></div>{f.score>0 ? <AlertTriangle size={16} className="text-amber-600"/> : <CheckCircle2 size={16} className="text-slate-400"/>}</div><p className="mt-2 text-xs leading-5 text-slate-600">{f.reason ?? 'No material signal detected for this factor.'}</p></div>)}</div></section>
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={TrendingUp} title="Recommended actions"/><div className="mt-3 flex items-center gap-2"><button onClick={()=>void createAction()} disabled={actionBusy} className="rounded-md bg-primary-700 px-3 py-2 text-xs font-medium text-white disabled:opacity-50">{actionBusy?'Creating…':'Create Review Action'}</button>{actionMessage&&<span className="text-xs text-slate-500">{actionMessage}</span>}</div><div className="mt-4 space-y-2">{project.recommendations.length ? project.recommendations.map((r,i)=><div key={r} className="flex gap-3 rounded-md bg-slate-50 p-3 text-xs text-slate-700"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-white text-[10px] font-semibold text-slate-500">{i+1}</span>{r}</div>) : <p className="text-xs text-slate-500">No specific action was generated because no risk factor was triggered.</p>}</div><p className="mt-4 text-[10px] text-slate-400">These recommendations are review guidance. A risk score is not proof of fraud or misconduct.</p></section>
      </main>
      <aside className="space-y-5"><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={MapPin} title="Evidence"/><div className="mt-4 space-y-3"><img src={sourceImage} alt="Project work" className="h-44 w-full rounded-lg object-cover border border-slate-200" onError={(e)=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-md bg-primary-700 px-3 py-2 text-xs font-medium text-white">Add work image<input type="file" accept="image/*" className="hidden" onChange={uploadImage}/></label><button onClick={randomImage} className="rounded-md border border-slate-200 px-3 py-2 text-xs font-medium text-slate-700">Random project image</button></div><Info label="Project image" value={customImage || text(raw.image) !== '—' ? 'Available' : 'Representative image'}/><Info label="Document" value={text(raw.document) === '—' ? 'Not available' : 'Available'}/><Info label="Work description" value={text(raw.work_description ?? raw.description)} /></div></section><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)]"><SectionTitle icon={Copy} title="Duplicate review"/><p className="mt-3 text-xs leading-5 text-slate-500">{project.factors.find(f=>f.id==='duplicate')?.reason ?? 'This project is not currently in a duplicate/similarity review group.'}</p><Link to="/duplicate-detection" className="mt-3 inline-block text-xs font-medium text-primary-700 hover:underline">Open duplicate analysis →</Link></section></aside>
    </div>
  </div>;
}
function Info({label,value}:{label:string;value:unknown}) { return <div className="min-w-0"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xs font-medium text-slate-700 break-words">{text(value)}</p></div>; }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>; }
function SectionTitle({icon:Icon,title}:{icon:typeof FileText;title:string}) { return <div className="flex items-center gap-2"><Icon size={16} className="text-slate-500"/><h2 className="text-sm font-semibold text-slate-900">{title}</h2></div>; }
function num(v: unknown): number | null { if(typeof v==='number'&&Number.isFinite(v)) return v; if(v==null||v==='') return null; const n=Number(String(v).replace(/[₹$€£,%\s,]/g,'')); return Number.isFinite(n)?n:null; }
