import { useMemo, useState } from 'react';
import { Download, FileJson, FileText, Printer, Table2, Eye, X, CheckCircle2, ShieldAlert, Search, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '@/components/common/PageHeader';
import { useCurrentDataset } from '@/services/datasetStore';
import { analyzeDataset } from '@/services/riskEngine';
import { formatCurrency } from '@/utils/formatters';
import { buildProjectFraudReportHtml, ensureFraudReports, getFraudRiskReports, type FraudRiskReport } from '@/services/fraudReportService';

function downloadFile(name: string, content: string, type: string) {
  const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a');
  a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function csv(rows: Record<string, unknown>[]) {
  if (!rows.length) return 'Project ID,Project Name,State,Risk Score,Risk Level\n';
  const keys = [...new Set(rows.flatMap(r => Object.keys(r)))]; const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  return '\ufeff' + [keys.join(','), ...rows.map(r => keys.map(k => esc(r[k])).join(','))].join('\n');
}
function escapeHtml(value: unknown) { return String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c] || c)); }
function riskCount(analysis: ReturnType<typeof analyzeDataset>, level: 'Low'|'Medium'|'High'|'Critical') { return analysis.riskDistribution.find(d => d.name.toLowerCase() === level.toLowerCase())?.value ?? 0; }

function buildExecutiveHtml(datasetName: string, analysis: ReturnType<typeof analyzeDataset>) {
  const top = [...analysis.projectRisks].sort((a,b)=>b.riskScore-a.riskScore).slice(0,30);
  const rows = top.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.projectId)}</td><td>${escapeHtml(p.projectName)}</td><td>${escapeHtml(p.state)}</td><td>${p.riskScore}</td><td>${p.riskLevel.toUpperCase()}</td><td>${formatCurrency(p.expenditure || 0)}</td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>MPLADS AI Monitoring Report</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:34px}h1{margin-bottom:4px}h2{margin-top:28px}.meta{color:#64748b;font-size:12px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.card{border:1px solid #dbe2ea;border-radius:10px;padding:14px}.num{font-size:22px;font-weight:700;margin-top:5px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #dbe2ea;padding:7px;text-align:left}th{background:#f1f5f9}.warn{margin-top:20px;padding:12px;border:1px solid #fed7aa;background:#fff7ed;border-radius:8px;font-size:12px}@media print{body{margin:18px}}</style></head><body><h1>MPLADS AI Monitor — Executive Monitoring Report</h1><div class="meta">Dataset: ${escapeHtml(datasetName)} · Generated: ${new Date().toLocaleString('en-IN')} · Model: ${escapeHtml(analysis.modelVersion)}</div><div class="cards"><div class="card">Projects<div class="num">${analysis.projects.toLocaleString('en-IN')}</div></div><div class="card">Critical<div class="num">${riskCount(analysis,'Critical')}</div></div><div class="card">High<div class="num">${riskCount(analysis,'High')}</div></div><div class="card">Expenditure<div class="num">${formatCurrency(analysis.totalExpenditure || 0)}</div></div></div><h2>Risk distribution</h2><p>Low: ${riskCount(analysis,'Low')} · Medium: ${riskCount(analysis,'Medium')} · High: ${riskCount(analysis,'High')} · Critical: ${riskCount(analysis,'Critical')}</p><h2>Top priority projects</h2><table><thead><tr><th>#</th><th>ID</th><th>Project</th><th>State</th><th>Risk</th><th>Level</th><th>Expenditure</th></tr></thead><tbody>${rows}</tbody></table><div class="warn"><strong>Human review safeguard:</strong> Risk scores and fraud-risk reports are screening signals, not findings of fraud or misconduct.</div></body></html>`;
}

export function Reports() {
  const ds = useCurrentDataset();
  const analysis = useMemo(() => ds ? analyzeDataset(ds) : null, [ds]);
  const [message, setMessage] = useState(''); const [preview, setPreview] = useState(false); const [fraudPreview, setFraudPreview] = useState<FraudRiskReport|null>(null); const [query,setQuery]=useState('');
  const fraudReports = useMemo(() => ds && analysis ? ensureFraudReports(ds, analysis) : getFraudRiskReports(), [ds, analysis]);
  const currentReports = fraudReports.filter(r => !ds || r.datasetId === ds.id).filter(r => `${r.projectId} ${r.projectName} ${r.project.state} ${r.project.constituency}`.toLowerCase().includes(query.toLowerCase())).slice(0,100);
  if (!ds || !analysis) return <div className="page-shell space-y-5"><PageHeader title="Reports" description="Generate auditable monitoring and project-risk reports."/><div className="panel p-10 text-center"><FileText className="mx-auto text-slate-400" size={30}/><h2 className="mt-3 font-semibold text-slate-900 dark:text-white">No processed dataset</h2><p className="mt-1 text-sm text-slate-500">Upload and process a dataset in Data Management first.</p></div></div>;
  const records = analysis.projectRisks.map(p=>({projectId:p.projectId,projectName:p.projectName,state:p.state,district:p.district,constituency:p.constituency,mp:p.mpName,agency:p.agency,riskScore:p.riskScore,riskLevel:p.riskLevel,status:p.status,sanctioned:p.sanctionedAmount,expenditure:p.expenditure,progress:p.progress,modelVersion:analysis.modelVersion}));
  const executiveHtml = buildExecutiveHtml(ds.fileName, analysis);
  const exportReport=(kind:'executive'|'projects'|'json')=>{ if(kind==='projects')downloadFile('mplads-project-risk-report.csv',csv(records),'text/csv;charset=utf-8'); if(kind==='json')downloadFile('mplads-ai-analysis.json',JSON.stringify({generatedAt:new Date().toISOString(),dataset:ds.fileName,summary:{projects:analysis.projects,low:riskCount(analysis,'Low'),medium:riskCount(analysis,'Medium'),high:riskCount(analysis,'High'),critical:riskCount(analysis,'Critical')},modelVersion:analysis.modelVersion,projects:records,fraudRiskReports:currentReports},null,2),'application/json;charset=utf-8'); if(kind==='executive')downloadFile('mplads-executive-report.html',executiveHtml,'text/html;charset=utf-8'); setMessage('Report exported successfully.'); };
  const printHtml=(html:string)=>{const w=window.open('','_blank','width=1100,height=800');if(!w){setMessage('Pop-up blocked. Allow pop-ups to print the report.');return;}w.document.write(html.replace('</body>','<script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body>'));w.document.close();};
  const downloadFraud=(r:FraudRiskReport)=>{downloadFile(`project-risk-${r.projectId}.html`,buildProjectFraudReportHtml(r),'text/html;charset=utf-8');setMessage(`Project risk report generated for ${r.projectId}.`);};
  return <div className="page-shell space-y-5">
    <PageHeader title="Reports" description="Generate auditable monitoring, project-risk and potential-fraud review reports."/>
    <div className="panel p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold text-slate-900 dark:text-white">Report workspace</p><p className="mt-1 text-xs text-slate-500">Source: <span className="font-medium text-slate-700 dark:text-slate-200">{ds.fileName}</span> · {analysis.projects.toLocaleString('en-IN')} projects · Model {analysis.modelVersion}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setPreview(true)} className="action-secondary"><Eye size={14}/>Preview</button><button onClick={()=>printHtml(executiveHtml)} className="action-secondary"><Printer size={14}/>Print / PDF</button></div></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">{[['Projects',analysis.projects.toLocaleString('en-IN')],['Critical',riskCount(analysis,'Critical')],['High',riskCount(analysis,'High')],['Expenditure',formatCurrency(analysis.totalExpenditure||0)]].map(([label,value])=><div className="kpi-card" key={label}><span className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</span><b className="mt-2 block text-xl sm:text-2xl text-slate-900 dark:text-white break-words">{value}</b></div>)}</div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[{title:'Executive Monitoring Report',desc:'Risk distribution, financial totals, model metadata and top priority projects.',icon:FileText,kind:'executive' as const},{title:'Project Risk Dataset',desc:'CSV containing every analysed project and explainable risk score.',icon:Table2,kind:'projects' as const},{title:'Machine-readable Analysis',desc:'JSON containing analysis, projects and generated fraud-risk reports.',icon:FileJson,kind:'json' as const}].map(({title,desc,icon:Icon,kind})=><div key={title} className="panel p-5 flex flex-col"><div className="flex items-center gap-2"><span className="rounded-lg bg-primary-50 p-2 text-primary-700 dark:bg-primary-950/50 dark:text-primary-300"><Icon size={18}/></span><h3 className="font-semibold text-slate-900 dark:text-white">{title}</h3></div><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400 flex-1">{desc}</p><button onClick={()=>exportReport(kind)} className="mt-4 inline-flex w-fit items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-xs font-semibold text-white hover:bg-primary-700"><Download size={14}/>Export</button></div>)}</div>
    <section className="panel p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-red-500"/><h2 className="section-title">Potential fraud-risk project reports</h2></div><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Reports are automatically created when the risk engine detects a configured fraud/anomaly signal.</p></div><div className="relative w-full lg:w-80"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project reports..." className="control w-full pl-9"/></div></div><div className="mt-4 table-scroll"><table className="data-table"><thead><tr><th>Project</th><th>Trigger</th><th>Risk</th><th>Reasons</th><th>Actions</th></tr></thead><tbody>{currentReports.map(r=><tr key={r.id}><td><div className="font-semibold text-slate-800 dark:text-slate-100">{r.projectName}</div><div className="text-[10px] text-slate-500">{r.projectId} · {r.project.state || '—'}</div></td><td><span className="rounded-full bg-red-50 px-2 py-1 text-[10px] font-semibold text-red-700 dark:bg-red-950/40 dark:text-red-300">{r.triggerType}</span></td><td><span className="font-bold text-red-600 dark:text-red-400">{r.riskScore}</span><div className="text-[10px] uppercase text-slate-400">{r.riskLevel}</div></td><td className="max-w-md"><div className="text-xs text-slate-600 dark:text-slate-300 line-clamp-3">{r.reasons.join(' · ')}</div></td><td><div className="flex flex-wrap gap-1"><button onClick={()=>setFraudPreview(r)} className="action-secondary"><Eye size={12}/>View</button><button onClick={()=>downloadFraud(r)} className="action-primary"><Download size={12}/>Report</button><Link to={`/projects/${encodeURIComponent(r.projectId)}`} state={{rowIndex:r.project.rowIndex}} className="action-secondary"><ExternalLink size={12}/>Investigate</Link></div></td></tr>)}{!currentReports.length&&<tr><td colSpan={5} className="py-10 text-center text-xs text-slate-500">No potential fraud-risk project reports for the active dataset.</td></tr>}</tbody></table></div></section>
    <section className="panel p-5"><div className="flex items-center gap-2"><CheckCircle2 size={18} className="text-green-500"/><h2 className="section-title">Risk distribution</h2></div><div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3">{(['Low','Medium','High','Critical'] as const).map(level=><div className="rounded-lg border border-slate-200 p-3 dark:border-slate-700" key={level}><div className="text-xs text-slate-500 dark:text-slate-400">{level}</div><div className={`mt-1 text-xl font-bold ${level==='Critical'?'text-red-500':level==='High'?'text-orange-500':level==='Medium'?'text-yellow-500':'text-green-500'}`}>{riskCount(analysis,level)}</div></div>)}</div></section>
    {message&&<div className="flex items-center gap-2 rounded-md bg-green-50 p-3 text-xs font-medium text-green-700 dark:bg-green-950/30 dark:text-green-300"><CheckCircle2 size={15}/>{message}</div>}
    {preview&&<div className="fixed inset-0 z-50 bg-slate-950/70 p-3 sm:p-6"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-3 sm:p-4"><div><h2 className="font-semibold text-slate-900">Executive Report Preview</h2><p className="text-xs text-slate-500">{ds.fileName}</p></div><button onClick={()=>setPreview(false)} className="rounded-md p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div><iframe title="MPLADS report preview" className="min-h-0 flex-1 w-full" srcDoc={executiveHtml}/></div></div>}
    {fraudPreview&&<div className="fixed inset-0 z-50 bg-slate-950/70 p-3 sm:p-6"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-3 sm:p-4"><div><h2 className="font-semibold text-slate-900">Project Risk Report</h2><p className="text-xs text-slate-500">{fraudPreview.projectId} · {fraudPreview.projectName}</p></div><button onClick={()=>setFraudPreview(null)} className="rounded-md p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div><iframe title="Project risk report preview" className="min-h-0 flex-1 w-full" srcDoc={buildProjectFraudReportHtml(fraudPreview)}/><div className="border-t p-3 flex justify-end gap-2"><button onClick={()=>downloadFraud(fraudPreview)} className="action-primary"><Download size={14}/>Download report</button><button onClick={()=>printHtml(buildProjectFraudReportHtml(fraudPreview))} className="action-secondary"><Printer size={14}/>Print / PDF</button></div></div></div>}
  </div>;
}
