import { useEffect, useState, type ReactNode, type ComponentType } from 'react';
import { CheckCircle2, Database, Gauge, Monitor, RefreshCw, RotateCcw, Save, Server, ShieldCheck, Copy, Mail as MailIcon } from 'lucide-react';
import { PageHeader } from '@/components/common/PageHeader';
import { useSettings, defaultSettings, type ThemeMode } from '@/hooks/useSettings';
import { useTheme } from '@/hooks/useTheme';
import { backendHealth, testAuthorityEmail } from '@/services/backendApi';
import { clearPersistedDataset, useCurrentDataset } from '@/services/datasetStore';

export function Settings(){
 const {settings,updateSettings,resetSettings}=useSettings(); const {setTheme}=useTheme(); const currentDataset=useCurrentDataset();
 const [draft,setDraft]=useState(settings); const [saved,setSaved]=useState(false); const [backend,setBackend]=useState<'unknown'|'online'|'offline'>('unknown'); const [checking,setChecking]=useState(false); const [testRecipient,setTestRecipient]=useState(''); const [emailTest,setEmailTest]=useState(''); const [testingEmail,setTestingEmail]=useState(false);
 useEffect(()=>setDraft(settings),[settings]);
 const patch=(p:Partial<typeof draft>)=>{setDraft(x=>{const next={...x,...p}; if(next.duplicatePotentialThreshold>=next.duplicateStrongThreshold) next.duplicatePotentialThreshold=Math.max(35,next.duplicateStrongThreshold-1); return next}); if(p.theme) setTheme(p.theme as ThemeMode); setSaved(false)};
 const save=()=>{updateSettings(draft);setTheme(draft.theme);setSaved(true)};
 const reset=()=>{resetSettings();setTheme(defaultSettings.theme);setDraft({...defaultSettings});setSaved(true)};
 const checkBackend=async()=>{setChecking(true);try{await backendHealth(draft.apiBaseUrl.trim());setBackend('online')}catch{setBackend('offline')}finally{setChecking(false)}};
 const testEmail=async()=>{if(!testRecipient.trim()){setEmailTest('Enter a recipient email address.');return;}setTestingEmail(true);setEmailTest('');try{const r=await testAuthorityEmail(testRecipient.trim());setEmailTest(r.sent?'SMTP test email sent successfully. Check the recipient inbox.':(r.error||'SMTP test failed.'));}catch(e){setEmailTest(e instanceof Error?e.message:'SMTP test failed. Start the backend and check SMTP configuration.');}finally{setTestingEmail(false)}};
 const requestNotifications=async()=>{if(!('Notification'in window)){patch({desktopNotifications:false});return;}const p=await Notification.requestPermission();patch({desktopNotifications:p==='granted'});};
 return <div className="max-w-screen-2xl mx-auto space-y-5"><PageHeader title="Settings" description="Configure appearance, duplicate detection, monitoring behaviour and backend connectivity."/>
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-primary-200 bg-primary-50 p-4 dark:border-primary-900/70 dark:bg-primary-950/30"><div><p className="text-sm font-semibold text-primary-900 dark:text-primary-100">Configuration is stored locally</p><p className="text-xs text-primary-700 dark:text-primary-300">Browser preferences persist in localStorage. No secret API key is stored by this panel.</p></div><button onClick={save} className="inline-flex items-center gap-2 rounded-md bg-primary-600 px-4 py-2 text-xs font-semibold text-white hover:bg-primary-700"><Save size={15}/>Save settings</button></div>
  {saved&&<div className="flex items-center gap-2 rounded-md bg-green-50 px-3 py-2 text-xs font-medium text-green-700 dark:bg-green-950/30 dark:text-green-300"><CheckCircle2 size={15}/>Settings saved successfully.</div>}
  <Section icon={Monitor} title="Appearance" description="Improve readability and control the dashboard visual density."><div className="grid gap-4 md:grid-cols-3"><Field label="Theme"><select value={draft.theme} onChange={e=>patch({theme:e.target.value as ThemeMode})} className="control w-full"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></Field><Field label="Density"><select value={draft.density} onChange={e=>patch({density:e.target.value as typeof draft.density})} className="control w-full"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="Font size"><select value={draft.fontScale} onChange={e=>patch({fontScale:e.target.value as typeof draft.fontScale})} className="control w-full"><option value="small">Small</option><option value="normal">Normal</option><option value="large">Large</option></select></Field></div></Section>
  <Section icon={Copy} title="Duplicate detection" description="These thresholds directly control the Step 2 duplicate screening engine."><div className="grid gap-4 md:grid-cols-3"><RangeField label="Strong match threshold" value={draft.duplicateStrongThreshold} min={60} max={95} onChange={v=>patch({duplicateStrongThreshold:v})}/><RangeField label="Potential match threshold" value={draft.duplicatePotentialThreshold} min={35} max={80} onChange={v=>patch({duplicatePotentialThreshold:v})}/><RangeField label="Amount tolerance (%)" value={draft.duplicateAmountTolerance} min={1} max={30} onChange={v=>patch({duplicateAmountTolerance:v})}/></div><p className="mt-3 text-[11px] text-slate-500">Recommended baseline: strong 70%, potential 50%, amount tolerance 10%.</p></Section>
  <Section icon={Gauge} title="Monitoring & tables" description="Control dashboard refresh behaviour and how many records are rendered in large tables."><div className="grid gap-4 md:grid-cols-3"><Field label="Rows per table"><select value={draft.maxRowsPerTable} onChange={e=>patch({maxRowsPerTable:Number(e.target.value)})} className="control w-full"><option value={50}>50</option><option value={100}>100</option><option value={250}>250</option><option value={500}>500</option></select></Field><Field label="Auto refresh"><select value={String(draft.autoRefresh)} onChange={e=>patch({autoRefresh:e.target.value==='true'})} className="control w-full"><option value="false">Off</option><option value="true">On</option></select></Field><Field label="Refresh interval"><select disabled={!draft.autoRefresh} value={draft.refreshIntervalMinutes} onChange={e=>patch({refreshIntervalMinutes:Number(e.target.value)})} className="control w-full disabled:opacity-50"><option value={5}>5 minutes</option><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>60 minutes</option></select></Field></div></Section>
  <Section icon={Server} title="Backend & SMTP" description="Configure the FastAPI service used by Action Center and real authority notifications."><div className="flex flex-col gap-3 md:flex-row"><Field label="API base URL" className="flex-1"><input value={draft.apiBaseUrl} onChange={e=>patch({apiBaseUrl:e.target.value})} className="control w-full" placeholder="http://localhost:8000"/></Field><div className="self-end flex gap-2"><button onClick={checkBackend} disabled={checking} className="action-secondary">{checking?<RefreshCw size={14} className="animate-spin"/>:<Server size={14}/>}Test connection</button></div></div><div className="mt-3 flex items-center gap-2 text-xs">Backend status: {backend==='online'?<span className="font-semibold text-green-600 dark:text-green-400">Online</span>:backend==='offline'?<span className="font-semibold text-red-600 dark:text-red-400">Offline</span>:<span className="text-slate-500 dark:text-slate-400">Not checked</span>}</div><div className="mt-4 rounded-lg border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold text-slate-900 dark:text-slate-100">SMTP delivery test</p><p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">SMTP credentials remain on the backend. This button sends a real test email without creating a project action.</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">Backend only</span></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={testRecipient} onChange={e=>setTestRecipient(e.target.value)} className="control flex-1" placeholder="your-email@example.com"/><button onClick={testEmail} disabled={testingEmail} className="action-primary">{testingEmail?<RefreshCw size={14} className="animate-spin"/>:<MailIcon size={14}/>}Send test email</button></div>{emailTest&&<p className="mt-2 text-xs font-medium text-slate-600 dark:text-slate-300">{emailTest}</p>}</div><p className="mt-2 text-[11px] text-slate-500 dark:text-slate-400">SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD and SMTP_FROM belong in <code>backend/.env</code>. Restart FastAPI after changing them.</p></Section>
  <Section icon={ShieldCheck} title="Notifications & privacy" description="Control browser notifications and whether the app should remain local-first."><div className="grid gap-4 md:grid-cols-2"><Toggle label="Desktop notifications" checked={draft.desktopNotifications} onChange={requestNotifications}/><Toggle label="Local-first processing" checked={draft.localProcessingOnly} onChange={()=>patch({localProcessingOnly:!draft.localProcessingOnly})}/></div></Section>
  <Section icon={Database} title="Local data" description="Manage the dataset currently stored in this browser. This does not delete your original CSV/XLSX file."
  ><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between rounded-lg border border-slate-200 p-4 dark:border-slate-700"><div><p className="text-xs font-semibold text-slate-800 dark:text-slate-100">{currentDataset ? currentDataset.fileName : 'No dataset loaded'}</p><p className="mt-1 text-[11px] text-slate-500">{currentDataset ? `${currentDataset.rows.length.toLocaleString('en-IN')} rows available to analytics.` : 'Upload a dataset from Data Management.'}</p></div><button disabled={!currentDataset} onClick={()=>{if(window.confirm('Clear the locally stored MPLADS dataset?')) void clearPersistedDataset()}} className="inline-flex items-center justify-center gap-2 rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-600 disabled:cursor-not-allowed disabled:opacity-40 dark:border-red-900/60"><RotateCcw size={14}/>Clear local dataset</button></div></Section>
  <Section icon={Database} title="Data safety" description="The app uses uploaded project data for analytics; settings do not modify the source dataset."><div className="rounded-md border border-slate-200 p-3 text-xs text-slate-600 dark:border-slate-700 dark:text-slate-300">Risk and duplicate results are screening signals. Keep human verification in the workflow before enforcement or financial action.</div></Section>
  <div className="flex flex-wrap justify-end gap-2"><button onClick={reset} className="inline-flex items-center gap-2 rounded-md border border-red-200 px-3 py-2 text-xs font-medium text-red-600 hover:bg-red-50 dark:border-red-900/60 dark:hover:bg-red-950/30"><RotateCcw size={14}/>Reset defaults</button><button onClick={save} className="inline-flex items-center gap-2 rounded-md bg-primary-600 px-4 py-2 text-xs font-semibold text-white hover:bg-primary-700"><Save size={14}/>Save settings</button></div>
 </div>;
}
function Section({icon:Icon,title,description,children}:{icon:ComponentType<{size?:number;className?:string}>;title:string;description:string;children:ReactNode}){return <section className="panel p-5"><div className="flex items-start gap-3"><div className="rounded-lg bg-slate-100 p-2 dark:bg-slate-800"><Icon size={18} className="text-slate-600 dark:text-slate-300"/></div><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p><div className="mt-4">{children}</div></div></div></section>}
function Field({label,children,className=''}:{label:string;children:ReactNode;className?:string}){return <label className={`block ${className}`}><span className="mb-1.5 block text-xs font-medium text-slate-700 dark:text-slate-200">{label}</span>{children}</label>}
function RangeField({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void}){return <Field label={`${label}: ${value}%`}><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full accent-primary-600"/><div className="mt-1 flex justify-between text-[10px] text-slate-400"><span>{min}</span><span>{max}</span></div></Field>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:()=>void}){return <button onClick={onChange} className="flex w-full items-center justify-between rounded-md border border-slate-200 p-3 text-left dark:border-slate-700"><span className="text-xs font-medium text-slate-700 dark:text-slate-200">{label}</span><span className={`relative h-5 w-9 rounded-full ${checked?'bg-primary-600':'bg-slate-300 dark:bg-slate-600'}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition-transform ${checked?'translate-x-4':'translate-x-0.5'}`}/></span></button>}
